run: ../bin/com/jrf/sampleapp/SimpleCalculator.class
	java -cp ../bin com/jrf/sampleapp/SimpleCalculator

../bin/com/jrf/sampleapp/SimpleCalculator.class: com/jrf/sampleapp/SimpleCalculator.java
	javac -d ../bin com/jrf/sampleapp/SimpleCalculator.java